### ISSUE TITLE
main `agent` CI is red: local `_Bus` fake missing `want_device` kwarg breaks strict-xfail scene test

### ISSUE THREAD

**Issue by btli** [joyfulhouse/brilliant-mqtt#120]
## Summary
`main` (currently `9562dda`) has a **red `agent` CI job** — a real regression, not a flake. Every open PR inherits it through the GitHub `pull_request` merge commit (`refs/pull/N/merge` = branch ∪ current main), so unrelated PRs (e.g. #115) show a red `agent` check they did not cause.

## Failing test
`tests/test_bus_watchdog_session.py::test_scene_subscribe_failure_never_reboots_a_healthy_panel`
```
TypeError: _Bus.on_change() got an unexpected keyword argument 'want_device'
  src/brilliant_mqtt/scene_bridge.py:208
```
(In full-suite ordering the same test can instead surface as `FileNotFoundError: .../owned-topics.json` — a later failure point once state leaks let `on_change` slip past; both are the same underlying defect.)

## Root cause — a semantic merge conflict between two already-merged features
- **#98** added a `want_device=` kwarg to `bus.on_change()` in production (`scene_bridge.py:208`, `bridge.py:233`, `bus.py`) and to the **shared** `FakeBus.on_change` (`tests/fakes.py`).
- **#118** (issue #87 follow-up) added `test_scene_subscribe_failure_never_reboots_a_healthy_panel`, decorated `@pytest.mark.xfail(strict=True, raises=AssertionError, ...)`.
- The test drives the **real** `SceneBridge.async_start()`, which calls `on_change(..., want_device=...)` against a **separate, local** `_Bus` fake in `tests/test_bus_watchdog_session.py` that #98 never updated. The result is a `TypeError`, and since `TypeError` is not the `AssertionError` the strict-xfail expects, xfail refuses to absorb it → **hard failure**.

The test only ever "passed" (as an xfail) back when it failed early with an `AssertionError`, before #98 changed the failure mode.

## Recommended fix (minimal)
1. In `tests/test_bus_watchdog_session.py`, give the local `_Bus.on_change` the same `want_device: Callable[[str], bool] | None = None` kwarg #98 already added to `FakeBus.on_change` (`tests/fakes.py`). This restores the intended `AssertionError`/xfail path.
2. Optionally broaden/remove the `raises=AssertionError` filter so a strict-xfail can't silently flip to a hard failure on an unexpected exception type again.

## Process follow-up (separate)
Local pre-commit runs the **branch head** (fewer tests) while CI runs the **merge commit** (branch ∪ main). That gap is why this is invisible locally. Consider a documented "merge-preview" gate: before finalizing, `git fetch origin refs/pull/<n>/merge && uv run pytest` (or merge `origin/main` locally first).

## Not caused by
PR #115 (issue #111, pre_bus stamp / pid<=1) — its branch head is fully green locally (1964 tests) and it touches none of `scene_bridge.py`/`bridge.py`/`fakes.py`/the scene test. It is a bystander whose merge-commit CI is red solely because of this main regression.

_Diagnosed via a read-only investigation at merge commit `5e07e1e`; reproductions in the analysis._
